name: mangrove-clay
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  
  # Geospatial libraries
  - geopandas>=0.14.0
  - rasterio>=1.3.0
  - shapely>=2.0.0
  - fiona>=1.9.0
  - pyproj>=3.5.0
  - cartopy>=0.22.0
  - contextily>=1.4.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Machine learning
  - scikit-learn>=1.3.0
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  
  # Jupyter ecosystem
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - ipywidgets>=8.0.0
  
  # Progress bars and utilities
  - tqdm>=4.65.0
  - click>=8.1.0
  - pathlib
  
  # Development tools
  - black
  - flake8
  - pytest
  - pre-commit
  
  # Optional: for advanced geospatial analysis
  - xarray>=2023.6.0
  - dask>=2023.6.0
  - zarr>=2.15.0
  
  # Pip packages not available in conda
  - pip
  - pip:
    - clay-foundation  # Clay foundation model (if available via pip)
    - earthengine-api  # Google Earth Engine (if needed)
    - --extra-index-url https://download.pytorch.org/whl/cpu  # CPU PyTorch if no GPU